server:
  port: 8005
spring:
  application:
    name: producer
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      probability: 1.0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/