server:
  port: 8007
spring:
  application:
    name: consumer-feign-hystrix
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
feign:
  hystrix:
    enabled: true

    